### ISSUE TITLE
[BE] DB Schema 작성

### ISSUE THREAD

**Issue by khk811** [42MVP/ft_transcendence#1]
### Description
draw.io 파일 DB 관계도를 작성합니다.

### TO-DO
- [ ] 관계선 정리
- [ ] 식별 관계 개선 고려
- [ ] User 테이블의 PK 타입을 string에서 int로 변경 (intra id -> 고유 숫자 id)
- [ ] intra id를 unique key로 둘지 고려
